apiVersion: v1
kind: Service
metadata:
  name: {{ include "maui.fullname" . }}
  labels:
    {{- include "maui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.appPort }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.nodePort }}
  selector:
    {{- include "maui.selectorLabels" . | nindent 4 }}
