apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-job
spec:
  template:
    spec:
      volumes:
      - name: db-mod-script-vol
        configMap:
          name: db-mod-configmap
      containers:
      - name: mysql-job
        image: mysql:5.7
        volumeMounts:
          - mountPath: /mysql-script
            name: db-mod-script-vol
        command:
        - /bin/sh
        - -c
        - |
          echo "script in /mysql-script"
          cp /mysql-script/db-mod.sh /tmp
          chmod +x /tmp/db-mod.sh
          /tmp/db-mod.sh
      restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-mod-configmap
data:
  db-mod.sh: |
      echo "db-mod.sh"
      date
      mysql -u root -ppassword -h mysql -e "ALTER USER user IDENTIFIED WITH mysql_native_password BY 'password'; FLUSH PRIVILEGES;"
      mysql -u root -ppassword -h mysql -e "USE db; CREATE TABLE greeting (msg VARCHAR(40) NOT NULL); INSERT INTO greeting(msg) VALUES('Hello World');"
